# -*- coding: utf-8 -*-
#
# Copyright (c) 2015 Guillaume Pellerin <guillaume.pellerin@ircam.fr>

# Manifeste is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# Manifeste is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Manifeste.  If not, see <http://www.gnu.org/licenses/>.

# Authors:
# Guillaume Pellerin <guillaume.pellerin@ircam.fr>

# version 1

var:
    image: debian:jessie
    volumes:
        - ./var/media:/srv/media
        - ./var/backup:/srv/backup
        - ./var/static:/srv/static
        - ./var/log/uwsgi:/var/log/uwsgi
        - ./var/log/nginx:/var/log/nginx
        - ./var/log/app:/var/log/app
        - ./var/log/cron:/var/log/cron
        - ./bin:/srv/bin
        - ./doc:/srv/doc
        - /srv/bower
    command: "true"

db:
    image: postgres:9.5
    volumes_from:
        - var
    volumes:
        - ./var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=noodFof2Kna

app:
    image: ircamweb/mezzo:latest-dev
    command: /bin/sh bin/app.sh --runserver
    volumes:
        - ./app:/srv/app
        - ./lib:/srv/lib
        - .git:/srv/.git
    volumes_from:
        - var
    expose:
        - "8000"
    ports:
        - "9010:8000" 
    links:
        - db
    environment:
        - DEBUG=False