version: '2'
services:
    app:
        image: ircamweb/mezzo:latest-dev
        command: /bin/sh bin/app.sh --runserver
        ports:
            - "9002:8000"
        env_file:
            - 'env/dev.env'
